/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * Task API
 * OpenAPI spec version: 1.0.0
 */

export interface Task {
  description: string;
  done: boolean;
  id: number;
  title: string;
}
