openapi: "3.0.0"
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:4010
    description: Local server
paths:
  /tasks:
    get:
      summary: Get all tasks
      operationId: getTasks
      tags:
        - "tasks"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
                example:
                  - id: 1
                    title: Task 1
                    description: Description 1
                    done: false
                  - id: 2
                    title: Task 2
                    description: Description 2
                    done: true
    post:
      summary: Create a task
      operationId: createTask
      tags:
        - "tasks"
      requestBody:
        description: Task object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: Task 1
                description: Description 1
                done: false
  /tasks/{taskId}:
    get:
      summary: Get a task
      operationId: getTask
      tags:
        - "tasks"
      parameters:
        - name: taskId
          in: path
          description: ID of task to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: Task 1
                description: Description 1
                done: false
        "404":
          description: Not Found
    put:
      summary: Update a task
      operationId: updateTask
      tags:
        - "tasks"
      parameters:
        - name: taskId
          in: path
          description: ID of task to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Task object to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: Task 1
                description: Description 1
                done: false
        "404":
          description: Not Found
    delete:
      summary: Delete a task
      operationId: deleteTask
      tags:
        - "tasks"
      parameters:
        - name: taskId
          in: path
          description: ID of task to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - description
        - done
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        done:
          type: boolean
    TaskRequest:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
